title: Welcome
properties:
  mode: "run-on-change" # Will run whenever this config changes
screens:
  first-screen:
    source: yafti.screen.title
    values:
      title: "Welcome to your custom OS"
      icon: "/path/to/icon"
      description: |
        This guided installer will help you get started with your new system.

  can-we-modify-your-flatpaks:
    source: yafti.screen.consent
    values:
      title: Welcome, Traveler!
      condition:
        run: flatpak remotes --columns=name | grep fedora
      description: |
        We have detected the limited, Fedora-provided Flatpak remote on your system, whose applications are usually missing important codecs and other features.

        This step will therefore remove all basic Fedora Flatpaks from your system. We will instead switch all core Flatpak applications over to the vastly superior, unfiltered Flathub.

        If you don't want to do this, simply exit this installer.
      actions:
        - run: flatpak remote-delete --system --force fedora
        - run: flatpak remote-delete --user --force fedora
        - run: flatpak remove --system --noninteractive --all
        - run: flatpak remote-add --if-not-exists --system flathub https://flathub.org/repo/flathub.flatpakrepo
        - run: flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo

  check-system-flathub:
    source: yafti.screen.consent
    values:
      title: Missing Flathub Repository (System)
      condition:
        run: flatpak remotes --system --columns=name | grep flathub | wc -l | grep '^0$'
      description: |
        We have detected that you don't have Flathub's repository on your system. We will now add that repository to your system-wide list.
      actions:
        - run: flatpak remote-add --if-not-exists --system flathub https://flathub.org/repo/flathub.flatpakrepo

  check-user-flathub:
    source: yafti.screen.consent
    values:
      title: Missing Flathub Repository (User)
      condition:
        run: flatpak remotes --user --columns=name | grep flathub | wc -l | grep '^0$'
      description: |
        We have detected that you don't have Flathub's repository on your current user account. We will now add that repository to your account.
      actions:
        - run: flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo

  configure-gnome-settings:
    source: yafti.screen.consent
    values:
      title: Configure GNOME settings
      description: |
        Next, we'll configure the following GNOME settings:

        - Turn on Night Light
        - Switch to Dark Mode
        - Remap Capslock to Backspace
        - Set Alt-Tab to switch between windows, instead of applications
        - Set custom background
        - Set Ctrl-Alt-T to launch 'distrobox enter main'
      actions:
        - run: gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
        - run: gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
        - run: dconf write /org/gnome/desktop/input-sources/xkb-options "['caps:backspace']"
        - run: dconf write /org/gnome/desktop/wm/keybindings/switch-applications "@as []"
        - run: dconf write /org/gnome/desktop/wm/keybindings/switch-windows "['<alt>Tab']"
        - run: gsettings set org.gnome.desktop.background picture-uri-dark "file:///usr/share/backgrounds/custom/background.jpg"

        # Bind ctrl-alt-t to launch 'distrobox enter main'
        - run: dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding '<Control><Alt>t'
        - run: dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command 'gnome-terminal -- distrobox enter main'
        - run: dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name 'distrobox'
        - run: dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"

  setup-distrobox:
    source: yafti.screen.consent
    values:
      title: Setup Distrobox
      condition:
        run: distrobox ls | awk -F '|' '{if (NR!=1) print $2}' | grep -E '\bmain\b'
      description: We will now setup and install a custom Distrox container.
      actions:
        - run: distrobox create -n main --image ghcr.io/extrange/my-distrobox

  install-gnome-extensions:
    source: yafti.screen.consent
    values:
      title: Install GNOME extensions
      show_terminal: true
      description: |
        We will now install the following GNOME extensions:

        - Clipboard Indicator
        - Dash to Dock
        - Fullscreen Avoider
        - GSConnect
        - Tailscale Status
        - Vitals
      actions:
        - run: gext install clipboard-indicator@tudmotu.com
        - run: gext install dash-to-dock@micxgx.gmail.com
        - run: gext install fullscreen-avoider@noobsai.github.com
        - run: gext install gsconnect@andyholmes.github.io
        - run: gext install tailscale-status@maxgallup.github.com
        - run: gext install Vitals@CoreCoding.com

  applications:
    source: yafti.screen.package
    values:
      title: Application Installer
      show_terminal: true
      package_manager: yafti.plugin.flatpak
      package_manager_defaults:
        user: false
        system: true
      groups:
        Core GNOME Apps:
          description: Core system applications for the GNOME desktop environment.
          default: true
          packages:
            - Calculator: org.gnome.Calculator
            - Calendar: org.gnome.Calendar
            - Camera: org.gnome.Snapshot
            - Characters: org.gnome.Characters
            - Clocks: org.gnome.clocks
            - Connections: org.gnome.Connections
            - Console: org.gnome.Console
            - Contacts: org.gnome.Contacts
            - Disk Usage Analyzer: org.gnome.baobab
            - Document Scanner: org.gnome.SimpleScan
            - Document Viewer: org.gnome.Evince
            - Extension Manager: com.mattjakeman.ExtensionManager
            - Font Viewer: org.gnome.font-viewer
            - Image Viewer: org.gnome.Loupe
            - Logs: org.gnome.Logs
            - Maps: org.gnome.Maps
            - Photos (Organizer): org.gnome.Photos
            - Sushi (Nautilus Previewer): org.gnome.NautilusPreviewer
            - Text Editor: org.gnome.TextEditor
            - Videos (Player): org.gnome.Totem
            - Weather: org.gnome.Weather
        System Apps:
          description: System applications for all desktop environments.
          default: true
          packages:
            - Fedora Media Writer: org.fedoraproject.MediaWriter
            - Flatseal (Permission Manager): com.github.tchx84.Flatseal
            - Font Downloader: org.gustavoperedo.FontDownloader
            - Mozilla Firefox: org.mozilla.firefox
        Custom:
          description: Additional applications I use
          default: True
          packages:
            - Calibre: com.calibre_ebook.calibre
            - GIMP: org.gimp.GIMP
            - Jellyfin: com.github.iwalton3.jellyfin-media-player
            - LibreOffice: org.libreoffice.LibreOffice
            - Moonlight: com.moonlight_stream.Moonlight
            - OBS Studio: com.obsproject.Studio
            - Obsidian: md.obsidian.Obsidian
            - Scrcpy: in.srev.guiscrcpy
            - Telegram: org.telegram.desktop
            - Ungoogled Chromium: com.github.Eloston.UngoogledChromium
            - VLC: org.videolan.VLC
            - VSCode: com.visualstudio.code
            - Zoom: flathub us.zoom.Zoom

        Gaming:
          description: "Rock and Stone!"
          default: false
          packages:
            - Bottles: com.usebottles.bottles
            - Discord: com.discordapp.Discord
            - Heroic Games Launcher: com.heroicgameslauncher.hgl
            - Steam: com.valvesoftware.Steam
            - Gamescope (Utility): org.freedesktop.Platform.VulkanLayer.gamescope
            - MangoHUD (Utility): org.freedesktop.Platform.VulkanLayer.MangoHud//22.08
            - SteamTinkerLaunch (Utility): com.valvesoftware.Steam.Utility.steamtinkerlaunch
            - Proton Updater for Steam: net.davidotek.pupgui2

  final-screen:
    source: yafti.screen.title
    values:
      title: "All done!"
      icon: "/path/to/icon"
      links:
        - "Install More Applications":
            run: /usr/bin/gnome-software
        - "Website":
            run: /usr/bin/xdg-open https://ublue.it
        - "Join the Discord Community":
            run: /usr/bin/xdg-open https://discord.gg/XjG48C7VHx
      description: |
        Start using your new OS!
